### ISSUE TITLE
upstream patches

### ISSUE THREAD

**Issue by fossfreedom** [OpenMandrivaAssociation/budgie-screensaver#1]
Please can patches such as this be upstreamed back to the getsolus project?

https://github.com/OpenMandrivaAssociation/budgie-screensaver/commit/2ef20faf38da993275b62ba8ccef82a50e09a68b

**Comment by AngryPenguinPL** [comment]
This patch is broken. It comes from old gnome-screensaver and looks like it is no longer needed in g-s fork called budgie-screensaver. Trying to apply it after merge g-s to b-s but it failed anyway. Need to drop it.
